site_name: "dimstack"

repo_url: https://github.com/phcreery/dimstack

theme:
  # name: "material"
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            members_order: source
            filters: []
            show_bases: true
            show_source: false
            heading_level: 3
