[project]
name = "dimstack"
version = "0.1.0"
description = ""
authors = [
    {name = "phcreery", email = "phcreery@gmail.com"},
]
dependencies = [
    "pandas>=1.5.2",
    "matplotlib>=3.5.2",
    "jinja2>=3.1.2",
    "latexify-py==0.2.0",
]
requires-python = ">=3.8, <3.11"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "black>=23.1.0",
    "ruff>=0.0.254",
    "pkginfo>=1.9.6",
    "jupyter>=1.0.0",
    "jupyterlab>=3.6.1",
    "jupyterlite-core>=0.1.0b19",
    "jupyterlite-pyodide-kernel>=0.0.5",
]

[tool.black]
line-length = 160

[tool.ruff]
# Same as Black.
line-length = 160

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]

[tool.pdm.scripts]