[project]
name = "dimstack"
version = "0.1.0"
description = ""
authors = [
    {name = "phcreery", email = "phcreery@gmail.com"},
]
dependencies = [
    "cowsay>=5.0",
    "colorama>=0.4.6",
    "black>=23.1.0",
    "pint>=0.20.1",
    "pandas>=1.5.3",
    "numpy>=1.24.2",
    "flake8>=5.0.4",
    "jupyterlab>=3.6.1",
    "jupyterlite>=0.1.0b18",
    "matplotlib>=3.7.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[flake8]
max-line-length = 120

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]

[tool.pdm.scripts]